### ISSUE TITLE
How to generate optimal LUT of FAID for different degree variable nodes for LDPC?

### ISSUE THREAD

**Issue by ze-ta** [gsw4869/gsw4869#1]
Hi, greetings from ze-ta! I've read paper 'Non-Surjective Finite Alphabet Iterative Decoders', but still fell pullzed of generating optimal LUT for different degree variable nodes, in the paper, for NS-FAID-433 decoder, for dv = 2, its lut is [0 1 2 3 4 5 6 7], and for dv = 3, its  LUT becomes to [0 1 1 3 3 3 7 7], ..., the author says that they obtain these LUT and gain factor $mu$ via DE, but details still remain closed, so could you give some matlab scripts for generating these LUTs and $mu$s, great thanks!
B.R.

**Comment by gsw4869** [comment]
Sorry, since the details of the original paper were not clear enough, I don't have these scripts either. For me, I just try different LUTs and combinations to find which is better.
